print("CLASE PRINT")
print("print sirve para 'imprimir texto' (Es como un debug.log)")
print('Hola mundo, te digo "hola"')
print('100 + 50')
print("El resultado es: ",100 + 50)

print("---------------------------------")
print("CLASE STRING")
print('String = cadena de texto que se encuentra entre ""')
print("Este signo \\ es una barra invertida \nAl usar \\ el siguiente caracter se escribe de forma literal sin importar que sea \n Se puede imprimír mas de una linea en un solo print usando \\n \n Poniendo \\t se genera un tab (salta 4 espacios)")
print("Hola " + 'Tilin')
print("Me llamo \"Tilin\"")
print("Esta es una linea \n y esta es otra linea")
print("\tEsta es la tercera linea")
print('this isn\'t a number')

print("---------------------------------")
print("CLASE INPUT")
print("input = funcion que permite meter información mediante el teclado")
print(input("¿Qué estás estudiando?"))
print(input("¿En qué país vives?"))
print(input("Escribe tu nombre:")+" "+input("Escribe tu apellido:"))
print("Tu nombre es " + (input("Escribe tu nombre: ")) + " " + (input("Escribe tu apellido: ")))

